
package client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersonalIncomeTaxCalculatorService", targetNamespace = "http://example/", wsdlLocation = "http://localhost:9000/PersonalIncomeTaxCalculator?wsdl")
public class PersonalIncomeTaxCalculatorService
    extends Service
{

    private final static URL PERSONALINCOMETAXCALCULATORSERVICE_WSDL_LOCATION;
    private final static WebServiceException PERSONALINCOMETAXCALCULATORSERVICE_EXCEPTION;
    private final static QName PERSONALINCOMETAXCALCULATORSERVICE_QNAME = new QName("http://example/", "PersonalIncomeTaxCalculatorService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/PersonalIncomeTaxCalculator?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONALINCOMETAXCALCULATORSERVICE_WSDL_LOCATION = url;
        PERSONALINCOMETAXCALCULATORSERVICE_EXCEPTION = e;
    }

    public PersonalIncomeTaxCalculatorService() {
        super(__getWsdlLocation(), PERSONALINCOMETAXCALCULATORSERVICE_QNAME);
    }

    public PersonalIncomeTaxCalculatorService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONALINCOMETAXCALCULATORSERVICE_QNAME, features);
    }

    public PersonalIncomeTaxCalculatorService(URL wsdlLocation) {
        super(wsdlLocation, PERSONALINCOMETAXCALCULATORSERVICE_QNAME);
    }

    public PersonalIncomeTaxCalculatorService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONALINCOMETAXCALCULATORSERVICE_QNAME, features);
    }

    public PersonalIncomeTaxCalculatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonalIncomeTaxCalculatorService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonalIncomeTaxCalculator
     */
    @WebEndpoint(name = "PersonalIncomeTaxCalculatorPort")
    public PersonalIncomeTaxCalculator getPersonalIncomeTaxCalculatorPort() {
        return super.getPort(new QName("http://example/", "PersonalIncomeTaxCalculatorPort"), PersonalIncomeTaxCalculator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonalIncomeTaxCalculator
     */
    @WebEndpoint(name = "PersonalIncomeTaxCalculatorPort")
    public PersonalIncomeTaxCalculator getPersonalIncomeTaxCalculatorPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://example/", "PersonalIncomeTaxCalculatorPort"), PersonalIncomeTaxCalculator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONALINCOMETAXCALCULATORSERVICE_EXCEPTION!= null) {
            throw PERSONALINCOMETAXCALCULATORSERVICE_EXCEPTION;
        }
        return PERSONALINCOMETAXCALCULATORSERVICE_WSDL_LOCATION;
    }

}
